### ISSUE TITLE
Nuxt start error

### ISSUE THREAD

**Issue by cretueusebiu** [motia/multiple-nuxt-apps-example#1]
I've added the following scripts:

```json
"forum:build": "nuxt build --config-file apps/forum/nuxt.config.js",
"forum:start": "nuxt start --config-file apps/forum/nuxt.config.js",
```

After I run build and start I get this error:

No build files found, please run `nuxt build` before launching `nuxt start`

Any idea ?

**Comment by motia** [comment]
I found that the `nuxt-start` and `nuxt-generate` scripts don't recognize `--config-file` command, which causes problems parsing arguments.

For now, you have to create your own scripts forcing the rootDir and the config file to take the correct values

    var rootDir = process.cwd()
    var nuxtConfigFile = resolve(rootDir, process.argv[3])

However, I checked nuxt development branch and it seems they fixed it, so no need to report. We have to be patient for the next release :)
