### ISSUE TITLE
Shared components/instances

### ISSUE THREAD

**Issue by rasyidly** [motia/multiple-nuxt-apps-example#2]
Hi @motia 
can u teach me how to create shared components/instances (so i can access in blog/forum pages, without duplicated components/instances) ? give me an example code..

**Comment by motia** [comment]
Hi @ngodink , for that you can use a symbolic link to do it quickly.
First, create the shared folder in the root directory.
Then, in each app folder, create a symlink that points to the shared folder.
   `ln -s ../../shared shared`
And that is all, you can use the shared modules normally
`import utils from '~/shared/utils`

**Comment by rasyidly** [comment]
thanks @motia for your solution, it works ! :)
but i have alternative solution, it is editing nuxt.config.js in each folder like

```
var path = require('path')
module.exports = {
  ...
  extend (config, ctx) {
    config.resolve.alias['~shared'] = path.join(__dirname, '../../shared')
  }
}
```
note: `../../shared` is a directory which i place shared folder from nuxt.config.js
so, i can use shared file (like: components, pages, etc.) in plugin folder with:
```
import utils from ~shared/utils
```

**Comment by motia** [comment]
great solution, that is even simpler.

**Comment by cve** [comment]
what about ~assets and /static?
