### ISSUE TITLE
Run components on the same page

### ISSUE THREAD

**Issue by edum18** [motia/multiple-nuxt-apps-example#3]
How would be the solution to run an app on the same page as the "master" app?

My "master" app page has:
- a top menu with the apps list, that never changes
- a container that has to contain the "child" apps content.

**Comment by motia** [comment]
Hi, @edum18 , I don't think it is possible to nest apps. 
But you can use an `<iframe>` html tag pointing to the child apps, though should consider its limitations on the latter.

An other solution would be to wrap the nested apps as modules. Then map the pages in the module into the master app. This may be a bit tedious as you need to be quite familiar with nuxt modules api and internals and resolve any path issues.

**Comment by edum18** [comment]
@motia I see, thanks for the tip, I'll see what I can do with nuxt modules
